/** ELIMINA L'UTENTE MAP SE VIENE TROVATO **/
DROP USER IF EXISTS map;

/** RICREA L'UTENTE MAP CON PASSWORD MAP **/
CREATE USER 'map' IDENTIFIED BY 'map';

/** CREA IL DATABASE map SE NON ESISTE GIA' **/
CREATE DATABASE IF NOT EXISTS MAP;

USE MAP;

/** DA I PRIVILEGI ALL'UTENTE MAP VERSO IL DATABASE MAP **/
GRANT ALL PRIVILEGES ON MAP.* TO 'map'@'%';

/** CREA UNA TABELLA DI ESEMPIO provaC **/
DROP TABLE IF EXISTS provaC;

CREATE TABLE provaC(
    X varchar(10),
    Y float(5,2),
	C float(5,2)
);

INSERT INTO provaC VALUES('A', 2, 1);
INSERT INTO provaC VALUES('A', 2, 1);
INSERT INTO provaC VALUES('A', 1, 1);
INSERT INTO provaC VALUES('A', 2, 1);
INSERT INTO provaC VALUES('A', 5, 1.5);
INSERT INTO provaC VALUES('A', 5, 1.5);
INSERT INTO provaC VALUES('A', 6, 1.5);
INSERT INTO provaC VALUES('B', 6, 10);
INSERT INTO provaC VALUES('A', 6, 1.5);
INSERT INTO provaC VALUES('A', 6, 1.5);
INSERT INTO provaC VALUES('B', 10, 10);
INSERT INTO provaC VALUES('B', 5, 10);
INSERT INTO provaC VALUES('B', 12, 10);
INSERT INTO provaC VALUES('B', 14, 10);
INSERT INTO provaC VALUES('A', 1, 1);
